defaults: &defaults
  adapter: postgresql
  # database: dchq_dss
  username: postgres
  password: rajneesh
  encoding: utf8
  host: localhost

development:
  database: dchqone_development
  <<: *defaults

test: &test
  database: dchqone_test
  <<: *defaults

production:
  database: dchqone_dss
  <<: *defaults
