defaults: &defaults
  adapter: postgresql
  # database: dchq_dss
  username: postgres
  password: iteron01 
  encoding: utf8
  host: localhost

development:
  database: ddchq_27062018
  <<: *defaults

test: &test
  database: dchqone_test
  <<: *defaults

production:
  database: ddchq_27062018
  <<: *defaults
